openapi: 3.0.0
info:
  description: "This is Alphacode sLLM Model Server Endpoint"
  title: "sllm endpoint"
  version: 1.0.0
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://34.70.67.174:8080
paths:
  /querytext:
    post:
      summary: Submit text data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskId: 
                  type: string
                styleGuideId:
                  type: string
                forbiddenWordDicId:
                  type: string
                mmsId:
                  type: string
                dictionaryId:
                  type: string
                text:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: A successful response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden

  /queryfile:
    post:
      summary: Upload a CSV file with metadata
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to upload
                taskId: 
                  type: string
                  description: The task ID
                styleGuideId:
                  type: string
                  description: The style guide ID
                forbiddenWordId:
                  type: string
                  description: The forbidden word ID
                mmsId:
                  type: string
                  description: The MMS ID
                dictionaryId:
                  type: string
                  description: The dictionary ID
      responses:
        200:
          description: A successful response
        400:
          description: Bad Request
        401:
          description: Unauthorized
        403:
          description: Forbidden
