openapi: 3.0.0
info:
  description: "This is Alphacode sLLM Model Server Endpoint"
  title: "sllm endpoint"
  version: 1.0.0
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://34.70.67.174:8080
paths:
  /querytext:
    post:
      summary: Submit text data
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                taskId: 
                  type: string
                styleGuideIds:
                  type: array
                  items:
                    type: string
                forbiddenWordDicIds:
                  type: array
                  items:
                    type: string
                mmsIds:
                  type: array
                  items:
                    type: string
                dictionaryIds:
                  type: array
                  items:
                    type: string
                text:
                  type: array
                  items:
                    type: string
      parameters:
        - in: header
          name: API-Key
          schema:
            type: string
          required: true
          description: The API key to authenticate requests
      responses:
        200:
          description: Request successfully processed
        400:
          description: Invalid input or missing parameters
        401:
          description: Unauthorized - API key is missing
        403:
          description: Forbidden - API key is invalid

  /queryfile:
    post:
      summary: Upload a CSV file with metadata
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The CSV file to upload
                taskId:
                  type: string
                  description: The task ID
                styleGuideIds:
                  type: array
                  items:
                    type: string
                  description: The style guide IDs
                forbiddenWordDicIds:
                  type: array
                  items:
                    type: string
                  description: The forbidden word dictionary IDs
                mmsIds:
                  type: array
                  items:
                    type: string
                  description: The MMS IDs
                dictionaryIds:
                  type: array
                  items:
                    type: string
                  description: The dictionary IDs
      parameters:
        - in: header
          name: API-Key
          schema:
            type: string
          required: true
          description: The API key to authenticate requests
      responses:
        200:
          description: Request successfully processed
        400:
          description: Invalid input or missing parameters
        401:
          description: Unauthorized - API key is missing
        403:
          description: Forbidden - API key is invalid

  /v1/chat/completions:
    post:
      summary: Create chat completion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  minLength: 1
                  description: 입력 텍스트
                output_length:
                  type: integer
                  minimum: 1
                  maximum: 1024
                  description: 출력 텍스트의 최대 길이
                temperature:
                  type: number
                  minimum: 0
                  maximum: 2
                  description: 생성 텍스트의 다양성 조절 파라미터
                language_code:
                  type: string
                  enum: [KR, EN]
                  description: 입력 언어 코드
              required:
                - text
                - output_length
                - temperature
                - language_code
      parameters:
        - in: header
          name: API-Key
          schema:
            type: string
          required: true
          description: The API key to authenticate requests
      responses:
        200:
          description: Request successfully processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Data successfully added to the task queue"
        400:
          description: Invalid input or missing parameters.
        401:
          description: Unauthorized - API key is missing
        403:
          description: Forbidden - API key is invalid
          