swagger: '2.0'
info:
  description: "This is Alphacode sLLM Model Server Endpoint"
  title: "sllm endpoint"
  version: 1.0.0
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: alphacode.co.kr
basePath: /v1
paths: 
  /querytext:
    post:
      consumes:
      - application/json
      parameters:
      - name: SHA256
        in: header
        type: string
        required: true
        description: SHA256 hash key for authentication
      - name: body
        in: body
        required: true
        schema:
          type: object
          properties:
            text:
              type: array
              items:
                type: string
      - name: type
        in: query
        type: string
        required: true
        description: Type of query
      responses:
        200:
          description: A successful response
  /queryfile:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - name: SHA256
        in: header
        type: string
        required: true
        description: SHA256 hash key for authentication
      - in: formData
        name: file
        type: file
        description: The CSV file to upload
        required: true
        format: binary
      responses:
        200:
          description: A successful response

# Import hello function
import hello
